# Whenever you add a page to the docs folder, add it here too so it will be included in the final product.
# Format is "- Display Name: 'path/file.md'"
# It is already assumed that you are in the docs folder when specifying the path, so no need to preface the path with docs
# Use a hierarchial structure to specify pages in a subsection
# For example:
# - Views:
#     - View Inventory: 'views/intalling.md'
pages:
    - Home: 'index.md'
    - Getting Started: 'gettingstarted.md'
    - Basic Usage: 'basicuse.md'
    - Changing Your Password: 'changepass.md'
    - Views:
        - View Inventory: 'views/viewinv.md'
        - Create New Products: 'views/createproducts.md'
        - Sell Inventory: 'views/sellinv.md'
        - Update Products: 'views/receiveinv.md'
        - View Customers: 'views/viewcust.md'
        - View Sales: 'views/viewsales.md'
        - Admin: 'views/admin.md'

# Everything below this line should not need to be changed
site_name: TInventory User Manual
repo_url: https://github.com/TInventory/Program
theme: readthedocs
